### ISSUE TITLE
Implement functionality to read in DBN JSON generated using program analysis

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#17]
Todo: write functions to read DBN JSON from AST analysis and output DBN in delphi's internal representation.

**Comment by cl4yton** [comment]
I've create a json_dev branch and pushed an initial commit.  This included separating out a "notes" version (not legal json due to comments) and "raw" (non-"notes") version of the data example source .json files under data/program_analysis.

Something odd: I had to update the path handling in delphi/program_analysis/example_analysis.py : accessing the index 1 in Path(__file__).parents[1] fails.  I'm not sure why this behavior has changed.  Context: running this on my "temporary" laptop (roadrunner) running Mac OS X High Sierra with a fresh python 3.6.5 virtualenv built from delphi requirements.txt.

**Comment by adarshp** [comment]
Basically, the 'parents' attribute of the Path object gives the ancestors, reaching back to where the script was run from. This made it so that the script would work when called from an upper directory, but crash when it was run from the same directory as `example_analysis.py`. Thanks for catching that! I've deleted the commented lines and kept your modification.

**Comment by adarshp** [comment]
I did a little bit of refactoring on the `load_analysis.py` module - added type hints, moved the print statements under a 'main' block. In general, I was thinking that we may want to have a `delphi/scripts` or `delphi/apps` folder residing at the same level as `requirements.txt` and `setup.py` with concrete examples of usage of methods defined in `delphi/delphi`, which can act as an analogue of the 'lib' folder in C/C++ projects.
