### ISSUE TITLE
Fortran variable names clashing with Python keywords

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#194]
I encountered this in a DSSAT subroutine - there was a variable called `AS`, which got translated to Python as the variable `as`, which is a Python keyword, and so caused a syntax error. Minimum example that produces the error:

```fortran
  program main
      implicit none
      integer as
      as=1
      end program main
```

We should probably put some kind of workaround/guard for this kind of situation. In terms of priority, it's not the highest priority issue, but I felt like (and perhaps naively) that it might be low-hanging fruit.

**Comment by skdebray** [comment]
Yeah, this is something that has been in the back of my mind for some time now.  I'm glad it's no longer a hypothetical problem.

@hlim1 has been looking separately at the problem of identifying Fortran built-in function names and figuring out the appropriate Python targets.  This issue is related in the sense that both involve looking at a Fortran name to decide if (a) there's something special about the name; and (b) if so, what Python name it should map to.  For this reason, I've assigned it to @hlim1 instead of @pratikbhd.

@hlim1: you can tell if a name is a name is a Python keyword as follows:

```python
>>> import keyword
>>> print(keyword.kwlist)
```
Recognizing Python keywords using this approach is straightforward, and coming up with a corresponding non-conflicting name doesn't seem all that difficult either (e.g., map `as` to `as_`).  One thing we may want to discuss is any possible implication such renaming may have on matching up code entities with comments.

**Comment by hlim1** [comment]
@skdebray Thank you for the direction. I will use the keyword module in the pyTranslate to check for the Python keywords and modify the id from Fortran as necessary with an appropriate format as you suggested. I will handle this issue along with the built-in function names for the Python under the intrinsic-function branch.

**Comment by adarshp** [comment]
@hlim1 Has this been taken care of? If so I'll close the issue.

**Comment by hlim1** [comment]
@adarshp I thought I handled this case a long ago, but the code was not there... Anyway, I've added a quick fix and pushed it into the SIR-demo branch instead of creating a new branch to handle this case. So, it is not taken care of, so I will just close it. Thanks for checking back!

**Comment by adarshp** [comment]
> @adarshp I thought I handled this case a long ago, but the code was not there... Anyway, I've added a quick fix and pushed it into the SIR-demo branch instead of creating a new branch to handle this case. So, it is not taken care of, so I will just close it. Thanks for checking back!

Thanks!
