### ISSUE TITLE
assert failure in rectify.py

### ISSUE THREAD

**Issue by skdebray** [ml4ai/delphi#265]
`rectify.py` dies with an assertion failure when processing the input program in `delphi/scripts/SIR_demo/DiscreteSIR-simple.f` in branch `SIR-demo`.  The error message is:

```
+ python3.6 rectify.py tmp/DiscreteSIR-simple.xml
rectify.py:1814: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (
Traceback (most recent call last):
  File "rectify.py", line 3690, in <module>
    buildNewAST(filename)
  File "rectify.py", line 3629, in buildNewAST
    XMLCreator.parseXMLTree(child, cur_elem, newRoot, newRoot, traverse)
  File "rectify.py", line 2422, in parseXMLTree
    self.handle_tag_file(root, current, parent, grandparent, traverse)
  File "rectify.py", line 390, in handle_tag_file
    self.parseXMLTree(child, cur_elem, current, parent, traverse)
  File "rectify.py", line 2528, in parseXMLTree
    ), f"In the parseXMLTree. Currently, <{root.tag}> passed from <{parent.tag}> is not supported"
AssertionError: In the parseXMLTree. Currently, <prefix> passed from <file> is not supported
```

Unrelated: can you also take a look at the `SyntaxWarning` for line 1814?

**Comment by hlim1** [comment]
@skdebray I've fixed the error. The issue was that tags were not handled properly and there were other new tags that were not being handled previously, which are now properly handled and produces XML in the rectified version of XML.

However, I am getting a preprocessor error with the version in the master. The version I have in the goto_elimination branch produced the preprocessed file without error. Thus, I used that file to generate the OFP XML, and then the rectified XML.
 
`+ python3.7 preprocessor.py /Users/hlim1/Research/delphi/scripts/SIR_demo/DiscreteSIR-simple.f tmp/DiscreteSIR-simple_processed.f
Traceback (most recent call last):
  File "preprocessor.py", line 382, in <module>
    lines, comments = preprocess(inputLines)
  File "preprocessor.py", line 336, in preprocess
    return extract_comments(enum_lines)
  File "preprocessor.py", line 214, in extract_comments
    ), (line_type, line)
AssertionError: ('other', '      double precision function randbn(n, p)\n')`

Though translate.py is also producing an error, so I will look into it.

**Comment by skdebray** [comment]
@hlim1 The assertion failure in `preprocessro.py` is strange -- that reflects a bug that Pratik pointed out last week and which I've fixed.  The problem is actually in the file `syntax.py`.

Can you execute the shell command `grep 'PGM_UNIT =' syntax.py` ?  The output should be

```
PGM_UNIT = r"\s+\w*\s+(program|module|subroutine|(\w*\s*){0,2}function)\s+(\w+)"
```
If you see something different (e.g., the "{0,2}" is missing) you need to pull.

**Comment by hlim1** [comment]
@skdebray Hmm.. The branch was behind the fix, which is odd because issue_265 was newly created branch from the master that I created soon after I saw this issue. Anyway, I deleted the branch and recreated just in case. And, yes, the issue was addressed. Also, this issue with rectify.py is also addressed.

The error in translate.py is as like below:

```
+ python3.7 translate.py -f tmp/rectified_DiscreteSIR-simple.xml -g tmp/DiscreteSIR-simple_pickle -i ../../../scripts/SIR_demo/DiscreteSIR-simple.f
Traceback (most recent call last):
  File "translate.py", line 895, in <module>
    outputDict = translator.analyze(trees, comments)
  File "translate.py", line 827, in analyze
    ast += self.parseTree(tree, ParseState())
  File "translate.py", line 793, in parseTree
    prog += self.parseTree(node, state)
  File "translate.py", line 793, in parseTree
    prog += self.parseTree(node, state)
  File "translate.py", line 785, in parseTree
    return self.ast_tag_handlers[root.tag](root, state)
  File "translate.py", line 167, in process_subroutine_or_program_module
    subState = state.copy(subroutine)
  File "translate.py", line 48, in copy
    self.subroutine if subroutine is None else subroutine
  File "translate.py", line 42, in __init__
    if "args" in self.subroutine
  File "translate.py", line 41, in <listcomp>
    [arg["name"] for arg in self.subroutine["args"]]
KeyError: 'name'
```

I will look into the issue.

**Comment by hlim1** [comment]
@skdebray I made all necessary fixes in rectify.py, translate.py, and pyTranslate.py to produce XML AST and python IR. I requested for a PR, so please review it and let me know if I need to make any additional fix in any files. Thank you.

**Comment by skdebray** [comment]
@hlim1 Thanks for fixing the problem so quickly.  I have only a minor change to request -- a few lines seemed long, that's all.  

I'll wait for @adarshp and @pratikbhd to review before merging.

**Comment by hlim1** [comment]
@skdebray Thank you for the review. I've just made changes to the code to shorten them and resolve the request. If there are other issues that require additional fix after the review from  @adarshp and @pratikbhd, I will address them as well.
