### ISSUE TITLE
Handle Function Returns

### ISSUE THREAD

**Issue by stephensj2** [ml4ai/delphi#60]
The program analysis code does not yet handle function returns. This is in part because the handling of such returns requires a few non-trivial additions. As a note, a good resource on functions can be found here:
https://pages.mtu.edu/~shene/COURSES/cs201/NOTES/F90-Subprograms.pdf

The following additions must be made:

- [ ] Functions must be "contained" within programs or subroutines which are the only thing that can call them. Thus, functions must be scoped so that multiple definitions of the same name in different contains scopes will not interfere with each other. This can be done by renaming functions. I have a few notes on this as well: (1) I believe contains statements can be nested. (2) I'm not sure, but it might be possible to access local variables in the parent scopes.
- [ ] The value to return is encoded differently than most other languages. The return value is stored in a variable of the same name as the function. Thus, for a function foo, the return value is set by assigning foo = value. Logic that is aware of this will need to be added to properly translate to python.
- [ ] There is an actual return keyword that terminates a function/subroutine/program. A transformation will likely be necessary to preserve this behavior as I assume delphi expects an entire container/function to execute to its entirety. If that is the case, a program transformation will likely be necessary to preserve the return behavior.

**Comment by pratikbhd** [comment]
As of now, the function returns are handled up to the point of generating the python scripts. There are some design decisions that need to be made though for the layout of the pgm.json file. Currently, the DBN-JSON specification document does not specify how the function returns will be represented in the JSON file. In essence, both user-defined functions having function returns and built-in functions like max(), exp(), etc will be a __assign__ function type in the PGM representation. The source field for this __assign__ function spec will now be a function instead of a mathematical operation or a numerical assignment. 

How should we describe these functions within the "source" field of the __assign__ function spec such that it is self-defining? I thought of a representation that looks somewhat like this:

For a statement, EO = max(EO, 0.0001)
The __assign__ representation can be as follows:

{
      "name": "PEPTP__assign__EO_0",
      "type": "assign",
      "target": "EO",
      "sources": [{
            'name': 'max',
            'output': {},
            'input': [
                    { 'variable': 'EO',
                       'index': 5,
                    },
                   { 'type': 'literal',
                      'dtype': 'real',
                      'value': 0.0001
                   }
                  ]
}],
      "body": [
        {
          "type": "lambda",
          "name": "PEPTP__lambda__EO_0",
          "reference": 4
        }
      ]
    }

I think this defines the function max() independently within this block itself. Further feedback and discussion on this will be required.

**Comment by skdebray** [comment]
Hi everyone,

I'm glad this discussion is happening and helping push things forward.  I think the DBN-JSON spec should always be _the_ reference we can turn to at all times, and that the implementation of the translation should always be consistent with this document.  To that end, I suggest that before moving forward with any new implementation steps, we wait until this discussion has converged to an agreement that is reflected in the DBN-JSON document.

**Comment by pauldhein** [comment]
@pratikbhd what would happen to this naming schema if we saw the following line of code: `EO = max(EO, EO_prev, 0.0001)`? All of a sudden we have two variables and with this naming schema the key named "variable" in your sources object would overwrite one of the two variables with the other. Also the constant/literal value should be encapsulated in the lambdas.py file. For the function I defined above this is what should be generated in both the pgm.json and the lambdas.py:

## pgm.json
```json
{
      "name": "PETPT__assign__EO_3",
      "type": "assign",
      "target": "EO",
      "sources":[
           {"name": "max", "type": "function"},
           {"name": "EO", "type": "variable"}
      ],
      "body": [
        {
          "type": "lambda",
          "name": "PETPT__lambda__EO_3",
          "reference": 22
        }
      ]
    }
```

I decided that we should have the sources be a list because that will preserve order information (which we will need for the lambdas file).

## lambdas.py
```python
def PETPT__assign__EO_3(max, EO):
    EO = max(EO, 0.0001)
    return EO
```

**Comment by skdebray** [comment]
@pauldhein @pratikbhd Has this been settled?

**Comment by pauldhein** [comment]
@skdebray It appears that the change is present in the `pgm.json` file I got from @pratikbhd at our last meeting for `PLANT.for`, but I don't believe that code has been checked in yet, so we should hold off on closing this issue until that code is checked in to master. If this has already been done then we should close this issue.

**Comment by adarshp** [comment]
This seems to be resolved, so I'm closing this issue.
