### ISSUE TITLE
Migrate from file-based data flow to using internal Python data structures.

### ISSUE THREAD

**Issue by adarshp** [ml4ai/delphi#81]
We should move away from requiring intermediate files for program analysis and instead be writing functions to produce and consume Python internal data structures - this will help with integrating the program analysis components with the rest of Delphi.

**Comment by pauldhein** [comment]
While we may need to be extending the Open Fortran Parser (OFP), as noted in #82, we may also want to look into [this python wrapper](https://pypi.org/project/open-fortran-parser/) for OFP. If it can compile around our updated version then this may be a convenient way for us to have a purely pythonic system that makes it even easier to store all intermediate steps in the translation/analysis process as python data structures.

**Comment by adarshp** [comment]
@pauldhein - that wrapper looks like it would server our purposes nicely.

**Comment by pauldhein** [comment]
Pinging this because we will want to discuss this issue at our next meeting. (@skdebray and @pratikbhd I look forward to hearing your thoughts on this)

I did some exploration on this and it turns out that in order for our translated python code (from the fortran source) to stick around we need to write it out to a python file. That being said, here is my idea for how we can restructure the output from `for2py` in order to best suit our needs...

## for2py output v2.0

- Remove `<fortran-file-name>.py` -- We have no need for a python file that has all of the lambda functions rolled into one big function, except as a debugging step. We also could use the name with the `.py` ending for a better purpose. Let's write a script that can take the output from the files we actually need to generate and reconstruct the one large python function code if necessary.
    - This may be a good place to have comments: comments from the whole subroutine could be placed at the top/bottom of the file respectively and comments about single lambda functions (if any exist or when they are auto-generated 😉) may be placed as a normal docstring within the lambda function
- Rename `lambdas.py` to `<fortran-file-name>.py` -- This should be the only python code that is actually generated. A python file containing lambda functions for all the fortran code parsed from the original fortran file. The current naming schema of `lambdas.py` for everything is unsustainable since we are now going to have multiple lambdas files from different fortran files to deal with.
- Rename `pgm.json` to `<fortran-file-name>.pkl` -- Similar to the above, we need names that are specific to the fortran file that the code/information was generated from. Also using a pickle file will correspond directly to python objects that can also be kept alive in the pipeline as opposed to being loaded at startup (this is per @adarshp' request)
    - Using python's [inspect](https://docs.python.org/3.6/library/inspect.html) module we will add the function handler code to each element in the `functions` list. The function handler will be placed in a new field labeled `code` or something similar
    - The `body` tags should be cleaned up to rely only upon function `__name__` variables and whatever minimal amount of added documentation is necessary
- Remove `<fortran-file-name>.xml`, `<fortran-file-name>_processed.for`, `<fortran-file-name>_pickle` -- We simply have no need for these after the parsing step is complete (as far as I know)

That's all I have as far as an update for this task. Please give me some feedback on this so we can determine which of these ideas we should use and which we should drop.

**Comment by skdebray** [comment]
We can certainly have the front end create/retain whatever set of files best meets our needs.  I think it would be helpful to understand and articulate those needs clearly so that we're all on the same page.  Some thoughts:

* The `fname.py` file corresponding to each Fortran file `fname.for`.  This is important for debugging the front-end translation process.  I personally prefer to have this be generated directly from the Fortran source rather than via a two-stage process (Fortran source --> lambdas --> debuggable python code) because the latter introduces two distinct translation steps and therefore two possible sources for bugs.  However, if there is no further use for the `fname.py` file beyond our debugging, we can have it created via a command-line switch rather than as a default.  
  * *To discuss:* how I/O in the Fortran code fits into this picture.  I have the impression that we need to know about the top-level input and output variables and deal with I/O operations, e.g., for sampling-based sensitivity analysis; also, I suspect that some Fortran programs may write out files that are read by other Fortran files.  I also have the impression that the lambdas are intended for consumption by delphi through the DBN JSON file and that they should therefore be "pure" functions that don't contain I/O statements such as READ and WRITE.  If this is true then the lambdas don't contain all of the information about the Fortran code and so cannot be used to reconstitute the `fname.py` file corresponding to the input file `fname.for`.
* The pickle file produced by the front end.  From my perspective, this relates to three distinct issues that I think we should discuss and nail down: 
  * *Scalability.*  Joshua has brought this up more than once, so I assume it's important and we need to plan for it.  It isn't clear to me where the bottlenecks are and therefore what tradeoffs we need to think about.[1]  He did mention that the "real" code bases are ~10^5--10^6 lines of code, so my front-end design decisions have focused on trying to avoid reprocessing source files wherever possible -- i.e., saving intermediate results so that we can avoid having to recompute them (as one example, the source file ModuleDefs.for (about 1000 lines of Fortran code) is used in 429 different files in DSSAT).  The pickle file aims to save intermediate results in order to avoid recomputation.  
  * *Milestones.*  Some of our milestones, such as processing multiple modules in parallel [this relates back to scalability], tacitly assume that information can be produced and saved asynchronously for use by downstream processing.
  * *Workflow.*  I don't have a clear picture of which pieces of information gleaned from the Fortran source will be used by whom and in what way (this is a personal shortcoming).  My impression is that there are at least two distinct lines of work: (1) Fortran subprograms --> comments --> comment processing; and (2) Fortran subprograms --> ASTs --> sensitivity analysis in delphi via the DBN JSON file.  Accordingly, the pickle file aims to make it easy to capture these mappings for subsequent processing.  But if my understanding of the workflow is inaccurate, or if a different organization of information would make downstream processing easier, we can certainly do that.

[1] I take responsibility for this because so far the only program that we've been able to process completely, from end to end, is Jon's tiny CROP_YIELD program (94 lines of code).  I plan to get Joshua's toy example done next -- that's about 1000 lines of code, and hopefully will give us a better understanding  of where the scalability issues, if any, may be.

**Comment by adarshp** [comment]
@skdebray Absolutely agree about the ability to 'cache' results, so to speak, for large codebases. I don't think we necessarily need to do away with all intermediate files, but I do think it would be good to have the option to have a 'file-less' end-to-end information flow, especially for the purposes of testing and integration. This could be as simple as separating the file I/O parts of the code from the actual program analysis logic. I'll see if I can take a crack at it today.

**Comment by adarshp** [comment]
I think this issue can be safely closed - we have an end-to-end testing pipeline with Python internal data structures, with only one exception due to the fact that OpenFortranParser requires a fortran filename as an input, and does not have an API to consume strings/stdio. As for the wrapper, I looked into it a bit more, and it looks like we have already implemented its functionality into our code base.
